spring:
  application:
    name: hello-server

server:
  port: 8016


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8015/eureka/
  instance:
    hostname: localhost