spring:
  application:
    name: hello-client

server:
  port: 8017


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8015/eureka/
  instance:
    hostname: localhost